# Rename this file to languages.toml to enable multilingual support
[zh-cn]
languageName = "中文"
languagedirection = "ltr"
title = "闲云记"
weight = 1


[en]
languageName = "English"
languagedirection = "ltr"
title = "Yee Sky Trail"
weight = 2
